list_skin_color = ['TANNED','YELLOW','PALE','LIGHT','BROWN','DARK_BROWN','BLACK']

list_top_type = ['HAT','TURBAN','SHORT_HAIR_DREADS_01','SHORT_HAIR_SHAGGY_MULLET','SHORT_HAIR_SHORT_CURLY',
                 'SHORT_HAIR_SHORT_FLAT','SHORT_HAIR_SHORT_WAVED','SHORT_HAIR_SIDES',
                 'SHORT_HAIR_THE_CAESAR','SHORT_HAIR_THE_CAESAR_SIDE_PART'
                 'NO_HAIR','EYE_PATCH','WINTER_HAT1','WINTER_HAT2','WINTER_HAT3','WINTER_HAT4',
                 'SHORT_HAIR_DREADS_02','SHORT_HAIR_FRIZZLE','SHORT_HAIR_SHORT_ROUND']
list_top_type_girls=['LONG_HAIR_BIG_HAIR','LONG_HAIR_BOB',
                 'LONG_HAIR_CURLY','LONG_HAIR_CURVY',
                 'LONG_HAIR_FRIDA','LONG_HAIR_NOT_TOO_LONG',
                 'LONG_HAIR_MIA_WALLACE','LONG_HAIR_STRAIGHT','LONG_HAIR_STRAIGHT2',
                 'LONG_HAIR_STRAIGHT_STRAND','HIJAB','LONG_HAIR_BUN','LONG_HAIR_DREADS',
                 'LONG_HAIR_FRO','LONG_HAIR_FRO_BAND','LONG_HAIR_SHAVED_SIDES']
list_hair_color = ['AUBURN','BLACK','BLONDE','BROWN','BROWN_DARK',
                   'BLONDE_GOLDEN','PASTEL_PINK','PLATINUM','RED','SILVER_GRAY']
list_hat_color = ['BLACK','BLUE_01','BLUE_02','BLUE_03','GRAY_01','GRAY_02',
                  'HEATHER','PASTEL_BLUE','PASTEL_GREEN','PASTEL_ORANGE',
                  'PASTEL_RED','PASTEL_YELLOW','PINK','RED','WHITE']

list_facial_hair_type = ['DEFAULT','BEARD_MEDIUM','BEARD_LIGHT','BEARD_MAJESTIC','MOUSTACHE_FANCY','MOUSTACHE_MAGNUM']
list_facial_hair_color = ['AUBURN','BLACK','BLONDE','BLONDE_GOLDEN','BROWN','BROWN_DARK','PASTEL_PINK','PLATINUM','RED','SILVER_GRAY']
list_mouth_type = ['DEFAULT','TWINKLE']
list_eye_type = ['CLOSE','SQUINT']
list_accessories_type = ['DEFAULT','KURT','PRESCRIPTION_01','PRESCRIPTION_02','ROUND','SUNGLASSES','WAYFARERS']
list_clothe_type = ['BLAZER_SHIRT','BLAZER_SWEATER','COLLAR_SWEATER','GRAPHIC_SHIRT','HOODIE','SHIRT_CREW_NECK','SHIRT_SCOOP_NECK','SHIRT_V_NECK']
list_clothe_color = ['BLACK','BLUE_01','BLUE_02','BLUE_03','GRAY_01','GRAY_02','HEATHER','PASTEL_BLUE','PASTEL_GREEN','PASTEL_ORANGE','PASTEL_RED','PASTEL_YELLOW','PINK','RED','WHITE']
list_clothe_graphic_type = ['BAT','CUMBIA','DEER','DIAMOND','HOLA','PIZZA','RESIST','SELENA','BEAR','SKULL_OUTLINE','SKULL']
